# DAY 5 – 2019-07-30 – Belgians in Strasbourg

“Flip Flops! Or Flop Flops!” I am surprised about how morning stupidities can be so influencing. I was really sleep deprived and this thought came up to my mind at questioning myself if I wanted to wear the flipflops or the flop flops to Strasbourg. The sneakers might become too hot for the day, and I had the intuition that I would spend most of the time barefoot, as I had done all over the week, and as it was my plan for the rest of the days. I chose the flipflops. I went to the bus and I found you there, with an empty spot for me. I sat next to you, talked for a while, and then lied over your legs and played with your vagina. It was very reassuring to think that we were still together on that. For me, signs of affections were the confirmation of my hypotheses and a pacifier for my fears. You liked me, and I liked you. We arrived at the office where we had our departure five days ago. You kept on thinking about O., and I wasn’t paying much attention to that. I had told you that you could do as you pleased. I still felt secure with you. However, it wasn’t my favorite topic of conversation. In the office, the authoritarian boss of the organization and the journalist leaded the conversation, one of the best of the exchange. However, I quickly was silenced and got bored by the already mentioned topics. I had an idea that I considered worthwhile talking about, but I could only express it at the end, and I didn’t find a clear answer on it. Well, time for training then. I warm up my legs, work out my body, and observed how your levels of energy were constantly decreasing. I didn’t want to invade your life, and I let you be free. 

We went to the park, did an evaluation that for me felt meaningful, but for many people pointless. I kept training with my feet and legs with the sticks of the park and participating on the activity from time to time. The boss asked me whether I had managed other exchanges before and offered me to work together. Unlike the other facilitators, in half morning, he was intelligent enough to detect potential and put it on his favor, not against him. However, I didn’t have a very good intuition about that person, and I didn’t show a lot of enthusiasm when he mentioned it. We came back to the office, I played football, and then chilled on the floor, just to be kicked out by Son.. I couldn’t care less. I got annoyed by the 50€ but considering the money in my bank account, the lessons I was learning with my presence there were already paying off. 

We went to the Lebanese restaurant. We were all tired, but my tiredness was justified on the lack of food due to the fasting. Thus, after I ate, I recovered much of it. I was amused at seeing you eating on a restaurant after having been together sharing our food with our hands on the grass and knowing how little you could follow social standards. On the other hand, I was trying to not to think about Ma.’s behavior. She is Belgian, and that can explain many things. (I have a pretty strong prejudice about Belgians as selfish people). She has complained about the money of the transportation and the participation fee for about 30 minutes on the hall. She had been bugging M. and G. with her mistake, which I found especially unfair considering that the Croatians had had to pay more because of their association not because of any type of personal choice concerning luxury of transporation. I had also come from Brussels and I had only spent 35€. It was difficult for me to imagine someone expending almost 200€ only on the one-way tickets from Belgium to France. I am not sure how or why, but the organization covered the expenses of Ma.’s mistake, and after 30 minutes of complains that everyone had to hear and no negative consequence to her finances, she decided to reward herself and her great performance with a proper dish on the restaurant, social convention that I also profoundly disagree with. Anyway, I tried not to care. You were there, K. was there, Mar. was there, and I was tired. I thought that it was probably something personal. I have grown tired of listening to people complaining about capitalism without doing anything about it. I have grown tired of admiring people incongruences and then trying to moralize with intellectual ideologies that take individual sacrifices to be performed. I have been writing the whole day this text, and right now I was eating some boiled potatoes with vinegar and salt in a plastic recipient of a soup that I took from the trash the evening before leaving towards France. And still, I support a form of capitalism that distributes the wealth evenly and behaves more consciously with the natural resources. In the past, I consumed lots of information and complain for many years about the problems of our society, but I have discovered that I sleep better when my actions are congruent with my moral ideas, and when I am actively participating in changing the system. Hypocrisy is a bit of a harsh word, but not the most inaccurate one in certain situations. Capitalism stands for personal responsibility and the fact that each individual can make the best of the conditions where we are born. I have lived in Belgium 3 years of my life, and it is a bit of a pain to keep on seeing people that had never struggled accepting and being submissive to a system that devours the world. As we experienced with the chairs game, we in Europe are incredibly fortunate for having what we have. We are the richest of the planet, and specifically Belgium is a pretty wealthy country. The worst consequences of the climate change are starting to be paid by the poorest countries. While Belgium becomes the next Spain, in Chad, the drought keeps on killing thousands, and the typhoons of southeast Asia left millions homeless. Ma. could complain about her mistake buying the train tickets, annoy the Croatians with her pointless miseries, and then be rewarded and saved by an external organization; but buying a nice dish to celebrate it was a bit over the top for me. I learned silence; I learn non-contentiousness. I had you seated next to me with your little salad, and I couldn’t do other thing than offered you all my food. Ma. said that it was disgusting the fact that I sometimes eat directly from a can of beans when I am working on my office. Well, life is also built out of effort and sacrifices, not just nice restaurants and mistakes amended by the system people love to complain about.

After the food, I had energy again. I kept on training and pushing the limits of my body a bit further. Climbing the pillars and jumping like a puma. At some point you asked me what my chargers were, and I behaved transactional, and asked you about money. Obviously, it was a joke, and if you would have reminded me for half a second the number of things you were doing for me, I would have written a list on the spot for you. But you moved away, offended. I kept on training. In case you still want to know, these are some of my chargers: 

-	Love, water, food, air, meditation, movement, stretching, people, understanding, nature, writing, reading, learning… 

I was still a bit affected by the idea of you liking O. and your reiterative comments. It was my mind reminding me about my insecurities and my avoidant attachment. I put it off with more movement, more challenges, and sending you some compassion when I looked at how tired you were. I would have loved to spend the evening together if you would have asked me so. But you had started to manifest or letting me know that you needed some personal space from time to time. 

Anyways, the activity around the city started. I was in the group with R. and Li., which were great positive and good energies for me. On the other hand, Et., another Belgian, was the leader and he was clearly annoyed by my attempts of democratizing the situation taking part of their power away. He was also scared of not being able to control me, not only by my endless levels of energy, but by my lack of respect to the authority and rules. M. got surprised that I could shower on a handbasin on the toilet, which for me was the most obvious thing to do. I kept on jumping and moving and then the event of the tram happened. I was playing to say goodbye when Et. realized that he was far away from controlling me. He played violence. I played silent pride and cold revenge. He threatened me with expelling me from the exchange. M. T.  supported him whatever they said later. I swallowed my pride, my words, my being. I looked into his eyes asking him to relax while he was shouting at me, holding me by the arm. I asked people to remember the moment he invaded me physically, just so we were all in the same page if the situation evolved. I played it as cool as I could. I took my calendar and save a reminder for the 5th of August that stated my intentions of giving an extreme negative feedback with an explanation of what had just happened. Emotions come and go. As a psychologist I am very aware of that. But the consequences of an action should be maintained until the person has learned their lesson. I put my shawl over my head. I couldn’t do it in the Vipassana when I was feeling hopeless, lonely and depressed but that bunch of authoritarian fearful guys wouldn’t take me away the pleasure of withdrawing from life for a while. I listened to 10 minutes of binaural beats, focusing on my breath and letting the emotions develop and fade away. Mar. kept on interrupting me, because her discomfort at watching at me was more important than my feelings. I asked several times to leave me alone, but she couldn’t. Maybe she was trying to care for me, maybe she was just pacifying her inner turmoil at seeing me in such a strange and distressed way. After the 10 minutes, the record of Carlos and me in the forests of Belgium started to sound on my ears. I couldn’t help myself from smiling, laughing, loving, and glowing from inside. I felt so connected to Carlos, so supported by him, by his thoughts, by his ideas, by the love he randomly sends me from time to time. Carlos is a great human being, and I am incredibly lucky of having him on my life. And he was there in the tram, saving me from my thoughts, from my feelings, taking me away from that negative situation where I was trapped. I loved him so, so much, and I enjoyed so, so much, that it even felt better the realization that I was probably the person feeling the best of the whole tram after such a negative encounter. (Don’t get me wrong “such a negative encounter” means nothing compared to what you have gone through on your life, or to what so many others have and are suffering at this moment on the planet. It is just how the story is being written…). 

We went down the tram and it started raining. People protected themselves from the water falling from the sky, and I let it wet my cheeks. Latchka and others got closer and asked if everything was okay, if I should take care of my health because I could catch a cold. I thank them for caring and dismiss their advice. I shared some of my water with mint, and lemon that we have prepared on the restaurant. Another tram came and I laugh at R.’s plastic raincoat. Then, I teased R. and Li. explaining them how Indian people smoke weed in the name of Shiva. Eventually, I came back to my phone and wrote, to feel a bit more at peace, to feel more justice. I came up with this: 

> <center>**I WILL NOT TALK IN YOUR PRESENCE**</center> 
>
>If you touch me
>
>I'll get back my space
>
>Listening transparent noise
>
>Wearing the burka in the tram
>
>Feeling the rain on my face
>
>Sharing my holy water
>
>Thanking non needed care
>
>Admiring Milano's catwalks
>
>And smoking in the name of
>
>Bam Bam bole
>
>A priceless lesson for me
>
>May become an expensive one for you
>
>
>Forgive them father for they don't know what they do.
>
>Remain silent in their presence for they attack your words.
>
>Then I prepared some lines in case I was asked to discuss what had happened: 
>
>I'm using my right to refuse to talk with violent people.
>
>Until he apologizes and ask for forgiveness, I'll will not utter a word to a violent person.
>
>If you're interested in the content of my mind, I will do it outside of his presence.
>
>And I connected again with my warrior spirit.
>
>I don’t eat meat and I am always hungry. 
>
>I don’t mind biting; my teeth are trained. 
>
>And a witty paradox to lift up my intellectual mood. 
>
>I wish I could be extremely intolerant with violence, but violent people don't tolerate this type of extremism. 
>
>I also had the luck of doing some express therapy with Mar.
>
>How often do you appreciate breathing?

She surprised me a lot at her determined belief about me crying on the tram. I hadn’t cry. My eyes might had become red, as my face. Red of anger and unfairness. But I hadn’t cry. I wouldn’t mind admitting it, but it was simply inaccurate to say that I had. However, Mar. was a firm believer of the idea that I had cry and she seemed convinced on spread what she thought she had seen. I realized that miracles are not done by messiahs or prophets themselves, but by blind believers. Mar. seemed to change a bit from her first statement of “I hate everyone” to the one we agreed later of “I love everyone”. It felt superior to realized that I my mood had been transformed so quickly and that I was fully enjoying my walk. On the other hand, the selfishness attitude of Ma.’s wasn’t able to empathize with my mood or my emotional state at all. She even got annoyed by my lack of willingness of interacting and collaborating with the rest of the group. I took the chance to connect more with Mar., Cs., R. and Li.. I got sure to make it clear that I still was the guy with the loudest laugh, and the most positive attitude. They couldn’t silence me so easily. They couldn’t. My ego kept on growing and growing. We arrived at the city center and the group split. Old people on one side (R., Li., Lucya, Et.), Andrei by its own, and young people on the other side (Ma., Mar., Cs.). I didn’t want to be alone. I wanted to be with young people, just to feel young. Ma. tried to escape from me in several occasions. She first started walking with the girls, then mentioned that there were not enough tram tickets for everyone, and finally accepted that I wasn’t going to give up so easily. I also did it to annoy her a little bit. My ego was having fun around. I turned to my phone and my social media. I send message to my friends all over the world, connect on the distance with them, send them love, remind them that I was alive, and I was thinking about them. The girls were shopping, and I was having fun by my own. I felt really powerful. I reminded myself of all the things that were going right on my life: my job, my house, my finances, my friends, my personal development, my creative endeavors, my internet presence. A few kids and some grown-ups with low emotional control weren’t going to shake my foundations. After few shops I got bored, I saw that other people were together somewhere else on the city, and I wanted to meet them.

I went to the cathedral, but I arrived too early. I waited for them listening to the meditation. Send some love to the planet, gratitude to my being and the people of my life, and the rain took me out of the meditation in the right moment. Another of those synchronicities that I couldn’t explain you at the mountain. I saw the group of people that I was supposed to meet, but they hadn’t seen me. I stuck to them until my needs call me back. They were shopping, the rain was getting stronger and there was nothing to be done. I entered a bar, shitted, washed my face and mouth, and remembered that I wanted to buy condoms for everyone just to avoid any logistical limitations screw up a potential sex party. While I was running under the rain looking for an open pharmacy at 20.15, I had the feeling that I was again forcing the situation. The pharmacy was closed but there was a condom dispenser outside. I didn’t have cash. I went to the bank and they changed me a 10€ paper for coins. I think I spend about 12€ in condoms of different types and classes. Most of them are now in my bathroom, waiting for their occasion. It felt right to the extent that I wasn’t doing it for me. A good leader takes care of the members of their tribe. I was doing it for everyone. After my secret adventure, I caught the group back. I didn’t know where I was, where I had to go, when I had to be where, and how I was supposed to go. Logistics, you know. I ran barefoot under the rain, following the live location that Ah. has shared on WhatsApp. It felt like a spy in a James Bond movie. I found them, and then, let myself be taken to the restaurant. 

You were there. I didn’t feel like talking to anyone. I wanted to be understood, not asked and questioned about what had happened during the day. My ego was still pretty active, and you comment about O. touched me enough to not wanted to talk more with you. Besides, I was extremely tired. I hadn’t eaten almost anything during the day, just the nectarine that I had taken from the office before our lunch, and the durum falafel. I was on my limits. I tried to drink the tea, but you were talking Russian with K.. Anyway, it was a good excuse to let myself be taken away from reality. You asked me how my day had been, what my feelings were, and I told you: “I will answer in half an hour.”

I played the hypnosis track under the turban. I let my body alone and dove deep inside the dark places of my mind where beliefs are stored. I clearly had said to K. to tell anyone not to interrupt me. I trusted on her. I felt betrayed with each interruption, but I achieved forgiveness. She was K.. I couldn’t get angry with her. I got interrupted several times: the waitress, V., O.. Enough was enough. I learned my lesson. K. wasn’t taking care of me, I had to do it myself. When I hit O.’s face, people understood a bit better that I was a sleeping beast, not a dead mouse. The hypnosis kicked pretty strongly. I got awaked with a huge self-confidence, renewed energy and the impetus of conquering the planet once more. 

“You are such a liar”, you said. “You are such a lion”, I understood. I walked away feeling even more reinforced. 

I didn’t want to talk with anyone, not even with you. But you had saved the food for me. I said “Thank you”. I wanted to be separated from the group. I wanted to feel different, to feel distant. I was expecting the social committee to appear with the meeting on the back of the bus as we had agreed the previous day. I went to the back of the bus. No one appeared. I reminded O. not to touch me if I didn’t want, being assertive and trying to avoid any connotations of violence. I couldn’t find you on the bus when I got in. I could have tried to sit with you and talk about your day, but fate place me alone. I tried to write, and I wrote. I tried to sleep, and I couldn’t. When we arrived, I tried again to talk with you. I told O. to find you, but you were gone. I recompose myself, and left the bus calmly, still tired, and with the pain of the photosensitivity on my eyes but feeling like a lion walking on the savanna. No predators, only preys. The driver on the bus couldn’t rush me. I looked into his eyes and I thank him the patience. I felt extremely powerful. 

You appeared out of nowhere. But it was too late. I wanted to talk with you before. I wanted to know your mind. Still, you had been the person taking care of me, the one that had asked for a container and collected the food. I had to say thank you. But it was a sing of boastfulness more than one of gratitude. It was a cold thank you, not a felt one. You got the message.

I went inside and proved everyone that me and my body were still functioning no matter the conditions of our situations. Only with the nectarine, the durum, and a bite of an apple, after a day of walking and moving around the city, after the confrontation with Et. and M. T. , and after days of sleep deprivation, I did my workout routine. K. told me that looked like a broken computer. To me it looked like the ultimate proof of respect. It is funny how the same situation can be interpreted in such different ways for different people. 

I went to the shower, cleaned my clothes, wore my swimming pants and pullover, and went out to see what the people offered me. In. (UK) was there. In. was that person I hadn’t had the opportunity of talking enough with. I had just crossed a few words and listened to her comments on the sessions. It was clear that she wasn’t like the rest, that she was more mature, more intelligent, wiser, and probably also questioned her presence in that charade. I had offered her to participate with us in the social committee. She had politely rejected it twice, and I thought it was enough. However, that day on the hall she was there, willing to talk and mediate, genuinely curious to know about my version of the story. I shared it with them and the rest of you. I played my non-violent passive redundant, overly clear and precise way of communication, just so no one could tell me that I was being too direct or aggressive. I confronted Ma. a couple of times, as well as Mar. about their consumerist behavior. I willingly seek for help and advice from In., who told me things that I have already been told in the past, or that I was already aware of. Empathy, placing myself on the other person shoes, Socratic questions. I know them, but I rarely apply them. I thank In. for the effort. She talked about my social life in Belgium, and whether I had people to talk with. I confessed that the life of an expat sometimes gets difficult concerning fulfilling social relationships. Even more if you are the weird type I consider myself. I was going to start talking about how grateful and happy I felt for having met you and your undeniable role as pacifier and emotional supporter during the exchange when you stood up and left to the hall. It didn’t hurt, it was just bad timing.  Deep inside I really wanted you to listen to me indirectly admitting that you were a key piece in the puzzle of my balance. I wanted you to know that I still loved you and that I valued you. But you stood up and left. I told it anyways.

We talked a bit more and then went inside. I kept on praising In. for her social wisdom and made her consider that she the most important person of her life. I made her reflect on the way she talked to others and how she talked to herself. I couldn’t see it coming, but it seemed that those comments were a motivator for her to leave the next day. I was expelling another of my believers from the exchange. She had called me extraordinary, and then unconsciously and unwillingly I had facilitated her departure. Another asset left. We were becoming alone. 

It crossed my mind the idea of going to your room and lie with you. But Mar.’s mood and your need of distance made me avoid that option. I had the huge luck of having a deep conversation with In. (Portugal). My ego was still activated, and more than a compassionate and understanding psychologist, I was a pushing coach giving a wake-up call to a powerful dormant being. I showed In. my routines, my affirmations, my mindset, my warrior attitude, my respect towards my health, body, mind, and spirit. I was really tired after the day, the fasting and the workout. I was really sleep deprived and my brain couldn’t have rested. And still, my kindness forced me to stay awake and talk with In. while she shared her psychological struggles. I prioritized her well-being over mine. We talked for at least an hour about my pride, my ego, our relationships (you and me), her relationship with herself, with the project, with her family, and with her life. I helped as much as I could help her at that moment, and she recommended me that morning hugs are less invasive that night ones. I took the advice. We hugged. I was uplifted by the fact that she had opened up to me, that she had allowed herself to be touched and touch a man without any sexual implications, that she was a bit freer and more at peace. 

I was extremely tired. I went to my tatami on my room. Lied there and tried to sleep. But two meditation, and several binaural beats later my brain didn’t want to. It wasn’t only the somatization of the dermatitis in my hands; the whole experience was starting to infect my mind. I was suffering from insomnia, that type of negative insomnia that I was advising A. B. and B. about. The insomnia of an untamed mind in a stressful situation. 
