--- 
title: "Letter to Alissija 2019-08"
author: "Carlos Alcala a.k.a. Carlito Fluito"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib]
biblio-style: apalike
link-citations: yes
github-repo: carlitofluito/Alissija
description: "This is a the letter I wrote to Alissija after the ten days we spent together in August 2019"
---

# Preamble {-#preamble}

We found each other. 

We said goodbye. 

I thank the universe for all that happened in between.

## Hello Alissija

2019-08-06 04.15

Hello Alissija, 

Don’t expect the best letter. It is 4 am. I went to sleep early, woke up a couple of hours ago and spend all this time ordering papers and stuff from the exchange. 

Some of the things I will write here probably will sound repetitive for both of us, you and me, because we separated last night. However, for our future selves can be a great memory trigger. I probably switch to cheesiness from time to time and tell you the wonderful human being that you are. Lucky me that I won’t see your rolling eyes, facial expressions, harsh comments, and your favorite word for the Carlos you met in the project: “Distance”. I am also procrastinating. I am not sure which of the hundreds of things I have to do should be first. Since I want to start doing something productive, I think it is a good moment for your letter.

09.12 

Eventually, I meditated and then fall asleep. Now, I am in the train, going to the office to work as much as possible before Friday, when I have a meeting with my advisor. The procrastination of your letter is, as so many negative things, rooted on fear. The fear of leaving out things that I would like to remember, that I would like to immortalize. But in case of not writing anything, none of them will be saved, so, let’s try. 
I don’t know where to start. Maybe some of the most important words for me of this exchange are transformation, silence, compassion, surrender, secure attachment, relationship, trust… Many possibilities. Since this is a letter, I will write mostly about me, how I felt, thought and believed at different points, in a subjective way, and as much as I feel comfortable with. So, expect those parts that you don’t like from me: the “talking too much”, and the “selfishness” focus on my current and previous selves.
