# DAY 4 – 2019-07-29 – Censored for democracy

Obviously, there is no good tale without a change of direction in about the middle of it. Here is where we are.

It all started in the morning, I woke up, you woke up. You left, and I went down, getting ready to spread the “Truth News” of the day. But it was already too late. The fear was winning. Mir. found me and told me that the activity that she has praised the previous day was better not to be repeated again because some people have complained to her and disagreed with what I was saying. I couldn’t believe it. I soon realized that talk about fruits and drinking water was making some participants more uncomfortable than what I could have predicted. It was difficult for me to accept that there was a majority of people that disagreed with what I was saying. Mir. referred to them as “many participants”, or “many complaints”, or “a lot of people” and those were vague and inaccurate terms that I wasn’t going to believe so easily. Besides, she kept on pressing me to focus on their activities about Fake News and use my inexistent free time to try to gather the group and ask their opinion in what I was proposing. I assumed that she was making it really difficult for me to try to make an impact on the program. The day moved forward and that French guy appeared with his toolkit, his videos and his stuff. I was already pretty distant of the whole thing. I didn’t care about the content, I cared about the people. I focused on my text for the evening and make a couple of interesting questions during the session just so no one could complain about my participation or the lack of it on the project. I was getting distant in any case. We did some more activities, but I was still piss by the morning censorship. 

At some point I had the idea of the ballots. I wanted to first-hand fact-check Mir.’s words about the general rejection of my morning news and my “Awakening Scoops”. I played St. Thomas and I told to myself that seeing was believing. I made the ballots, spread them, and at some point, got censored again by Mir.. She took me by the arm and drag me outside to ask me what I was doing. “I am defending democracy. I am giving them voice, so they can tell me individually if they like or not what I say and what I do.” “You want to confront people face to face, but many people don’t want that” “Have you seen the world?” I asked, “Why do you think there are many far right-wing movements increasing all around the world? It is because people can only vote once every four years. Ask the population more often and adjust to their needs, adjust to what they want and then you will avoid a really dangerous outcome.” “But what do you want? I don’t want that the journalist come and then people show their red cards.” She was really afraid. “I am just giving them the most efficient non-violent and non-intrusive way of giving me automatic feedback that I can think of. It is just for me, although I would love that we would use it for many decisions.” I repeated that sentence a couple of times along the conversation, but she didn’t quite get it.

I was speaking in my clear and wordy tone, just being cautious about my words, trying not to sound violent, and letting my point clear. I had to repeat several times that what I was trying to do was giving them voices independently. But I assume they thought that I was organizing an uprising. In the organization, no one trusted me. But the participants vote green for the usage of the cards. I could have played more demagogic, and pushed the situation further, explaining them that we could get back the control of the exchange if we all moved in the right direction, but hopelessness, the topic I couldn’t talk in the news, won again on their hearts when the quick free time was over and we were trapped in another annoying and boring activity. K. was smarter, for her the day was great. She went to the mountain. For me, a continuous repression.  

In the reflection group, Et. took the role of A. B., first victim. It was obvious that they were trying, that they were making changes and that they were listening to what we were saying. But on the other hand, they didn’t trust on us. They were building the perfect “us vs. them” situation, even while implementing our feedback with 3 days of delay. Et. was a perfect scribe, and he took notes of our wishes and comments. Just to show him that we weren’t against, we all thank him his efficiency. 

On the evening, there was that organization fair. Before it started, M. T. let me read the text. I didn’t count with the support of any of the member of the organization, I merely didn’t have their censorship avoiding me doing it. I wasn’t alone because I had you and few others listening to my words, but I felt that I wouldn’t be able to do that for long. I read the political text that you had correct me. I also worked a bit on my voice and the way of communication. I read the text offering people to leave the room when they wanted. Many left, some stayed, and some of those that stayed were distracted. Thank them anyway for the effort. 

Later on, maybe the next day, you mentioned that you wouldn’t spend your free time listening to me. That also touched me. 

I went outside and meditated. I felt it coming when I visualized the future. I felt it running through my right arm, life was filled of wonderful things waiting for me. The fair started, a fair that I couldn’t care less about. We had talked about the possibility of expanding our relationship and how much you liked other participants. I was all-in to have my personal side-project that would end up in a collective manifestation of hedonism and love. But I rushed too much. I should have notice that not everyone was as open minded as I was, that not everyone was as familiar with physical contact as I was, and that not everyone can differentiate love from sex, and sex from love. I promoted and invited you to go ahead with the idea of including people in our sexual encounters as a proof of my trust on you, of my fidelity, of my personal secure approach at our relationship. Maybe, you took it as a lack of engagement, as a lack of interest towards you as a person. Who knows? Looking at the case with perspective, now is clear to me how I should have proceeded. Anyways, I worked out with O., and then we danced a bit guided by you. I interrupted you, rushed, and made them leave. Somehow, the other participants had prepared everything for us outside, putting the tatami and the blankets there. We went there to chill. I caress and touch Karolina out of caring and not exclusively out of sexual lust. We are all suffering souls in this planet. You were doing your thing with O. and G., and I felt secure by being there next to you, supporting you with my silent presence. 

G. was a bit too invasive with me, but I was letting him do, just to keep the vibe cool, relax and growing. Most of the people left, I arranged pretty much all the stuff that was outside because I had the energy to do it, and a good leader takes care of their group. G. played “last dick standing” and we end up kissing among the three of us. Kissing a boy is not the thing that I like the most, but I don’t mind if the cause was going to be bigger. I assume that that was also a mistake. 

The sky was beautiful, but the night was over. We said goodbye and we went to our different rooms. I was strange. I wasn’t sure about the direction that everything had taken in only one day. I had tried to give voice to the people but seemed to me that the people had already found their respective voices in their smartphones, drawings, and different forms of entertainment. You, my main supporter, had mentioned that the text I had written wasn’t that good. I had rushed the creation of a connection among the participants, making maybe a retrogression. I was confused. Anyways, it seemed that we had advanced at including G. in the game. I had the feeling that we could do great things if we collaborated properly. But did we?
