# DAY 7 – 2019-08-01 – Surrendering my soul to the world, making love with the universe

I woke up pretty refreshed. I found you outside, taking the sun on the tatami. I shared with you the story of Paola, the girl I didn’t kiss when I was 11. You spoke about your fears of attachment, your insecurities and your Don Juan syndrome that kept on destroying your relationships. You told me how you get bored often about relationships, and how you end up as soon as you feel they are not contributing anything new in your life. 

The sessions started and I had perfectly learned my lesson. You had told me the previous day not to waste my energy during the sessions. I took my laptop and started working on my website, on the things that I had neglected from my life, on reorganizing and bringing back my duties. The session was pretty productive. I kind of interact a couple of times, but the distancing I got from the whole thing felt really good. I wrote about attachment and answered the question that the anonymous participant had suggested me. 

I took another look at the envelope and thought that you had written the one with so many teachings that you had told me on the mountain. Empathy, compassion, writing, letting go… It seems that the author wasn’t you after all, but In. (Portugal). Thus, she kept on saving me from the shadows. 

My head was still a bit of a turmoil, and you seemed perfectly secure, perfectly fine, perfectly at peace. I was still digesting the lessons from the previous day. I asked you about how to control my attention, but you couldn’t answer. We separated and I end up in the church, where I had restrained my impulses of having sex with you in front of a cemetery. I told my group that I would focus on myself. I entered the church and practice anapana (attention on the breath) for 30 minutes, just listening and attending to my breath. I went out, we filmed the video, and then I started training. Visualizations arrived to me as the correct tool in the correct moment. I was able to land the cork after few attempts. It was incredible how powerful the mind is. All seemed a huge synchronicity. I was feeling strong and energetic again. I went to the hall, skip lunch and kept on training, kept on visualizing. It was wonderful how fast I could advance just by interiorizing the movement before attempting it. 

After the lunch, I finished the text, I gave it to In. for correction and proofreading, and publish it on the website together with the slow-motion video she had recorded. A super-productive day. I was feeling thrilled again. I had learned my lesson, got detached from the exchange, do my own, learn and grow. Everything was in order again. 

My. tried to talk with me for a while. She asked me if I was okay, if everything was going well, and she showed interest on me when she tried to speak about my main occupation in Spain, *“I am living in Brussels”*. I understood better the importance of inner control vs. outer control, and how I should give to people once they asked for something, not before. I mastered silence, I mastered surrender. I worked hard on my compassion which since the meditation of the previous day, I was starting to feel more clearly on my body. 

You did the energizer of killing hearts with the fingers. It was my small revenge to show you that I was back on the game, full mode and ready to play. It kept on confirming my expectations the fact that even Igor, physically fit and older than me, couldn’t touch me even once. I was feeling unbeatable. 

I kept on observing people during the sessions, and I found you groggy and tired. I wrote notes to many participants, to spread my thoughts on their envelopes, and I gave one to you with your own lesson: “Don’t waste energy on the sessions, save it for later”. I wanted you to be fresh for the night, just in case. I did my last laundry, and then, I package my stuff in the backpack. I had learned, and I was planning to leave. We share a moment on the bathroom, when I watched you wetting your nape. It was wonderful to be there, the two of us alone, feeling the sexual tension of the moment, and keeping myself on the distance, enjoying the pressure. 

I decided to keep on focus on myself. I told And. that if people asked about me, he could say that I had gone running. Telling that to And. would mean no further questions from him, and a disclosure just when the situation became publicly dramatic. 

I run up the mountain. I followed part of what we had done the previous day. I was actually looking for you, K. and Marte. I thought you had gone to the castle and I wanted to join. I kept on going up, much easier than the previous day. Barefoot, with high levels of attention and concentration, being very aware of my body, with my t-shirt on my head, keeping my thoughts together. I took an apple. I bit it. It was my jaw protector in case I fell. Also, it worked as a coping mechanism, and tension liberator each time thoughts and fears arrived at my mind about you or about our conversation of the previous day. The stones and the spines hurt, but not as much as before. I kept on running up the mountain, on following the path, because this time there was no need of extra-pain. Running I realized that pain can be a certain type of love for some people. The pain that you caused me while having sex, the pain that you had made me go through the previous day, the pain that your parents had given to you when you were a kid. I was a warrior again. I was a wild animal. I was a sapiens surviving and ready to fight. I took a shit somewhere close to the top of the hill. I cleaned my ass with the nature, just to prove myself that I was one with the environment. I took a shortcut across the hill. Climbing on my monkey style, using four extremities instead of two. I collected some glass, so there were less chances that the whole forest became ashes one day. I reached the castle. But I still wanted more. 

The apple had the perfect mark of my teeth. My fears, my rage, my focus was there on that apple. My silence was on the apple. I shouted a couple of times. Cries of monkey, screams of mammal, yells of ape. Once in the castle I devise a route for climbing. I had done few climbing exercises during the day, but I looked for the real experience. I climbed up the wall, higher and higher, like a lizard. I was deeply afraid, fully conscious that a bad movement, a moment of lost concentration, or a loose stone would mean the end of the adventure. I knew I was pretty alone in the top of the hill, that there was no one around, that no one knew where I was, and that a fell from that height would mean my direct disability if not my death. But I climbed anyway, and I observed the vistas feeling my fears and thoughts in the depths of my being. I bit the apple and calmed down. More extenuating that the hiking up the hill was to be there, fighting against my fears. I understood a bit better how fearful people need to sleep so much, why they are always tired. Fear was extremely tiring. Fear is highly consuming. I lied down on the top of the wall, with my hands and feet hanging on the void. I calmed down my heart and breath. Accepted that I didn’t need to go further to prove myself anything else, and calmly descend again to the ground.

I had risked my life. Consciously and willingly. I had detached from life. I was freer, more powerful, stronger, more alive. I was Carlito Fluito. The same that had contained his tears while being beating up to extenuation by you for hiking up a mountain that he never asked to hike. That Carlito Fluito was now a beast, a warrior, a fighter, a survival. I had run up the mountain, barefoot, as you had told me; I had empty my bowels like an animal; shouted and screamed like an ape; climbed like a lizard; observed the horizon like an eagle; and confronted my fears like a human. I was a fully spiritual being. I descended running. Wanting to arrive on time to the reflection group. The word of the day came to my head, clear and translucent. “Silence”. Silence would hack the system. “What was good today? What could have been better? What did you learn? What would you apply for the future?” Silence. My silence to all of you.


The reflection group was extremely ridicule. K. left for a phone call, you started piercing the paper, and when we started reading the objectives and goals, I couldn’t help myself but laugh aloud. It was like coming back to my 6 years old class. By no means, I was going to read that bullshit. I wrote that I had been born there and now and I left the paper. 

I was training my climbing skills on the hall with O. and G. when you arrived. I felt superior again. I felt strong. O. was trying the exercises that I was doing with ease. I had been working the whole day on my climbing skills, and we compared ourselves in front of you. We, males, are this type of beings that think that their bodies represent their masculine worth. I couldn’t like winning more. I couldn’t like improving myself more. I felt so strong, confident and secure that I was ready to come back to you. To play a bit and check if you were still the strong and quick minded devil that had caught me unguarded the previous day on the hike up the mountain. I bit my apple and looked at your eyes. I remained silent, smiling, enjoying the feelings of power and superiority. I had realized your relationship with pain. The puzzle had become something much more meaningful. Your games, your willing for playing, your desire of control, your sadistic way of having sex. I had caught you. You mentioned that you weren’t planning to have sex with anyone in that exchange, or at least with anyone that was present there. That meant you had O. on mind. I knew it. But you didn’t know what I had discover.

“I know what you want” I said. “Tell me”. “Not here, come on…”. I had rehearsed that dialogue on my mind while going down the mountain. We excuse G. for his presence, and we left the hall. “I feel like if I am walking my pet” I told you. I was ready to fight back. We looked into each other eyes, I kept on smiling, on playing with your distance, on biting your lips, your neck, on interiorizing the pain when you pounded down your nails on my chest, on grabbing your hair when you bit me on the arm. I got you. We were playing and then you were mine. You weren’t getting bored anymore, you were getting nervous because you were losing, you weren’t sure if you wanted to keep playing. You even broke the rules and threw my apple away. I breathed in and out. I didn’t care. My dick was hard. The same dick that couldn’t have had an erection in the mountain was ready to pierce you in revenge of the pain you have caused me. The same dick that you loved to introduced in the throat, that throat filled with mucous that weren’t able to leave your body, that throat where the sensations of annoyance and boredom manifested, that throat that someone with the minimal knowledge about chakras would identify as an energetic blockage on the Vishuddha center. You asked me if I wanted to hear your feelings. You had already mentioned that you wouldn’t have sex in the exchange, or maybe just with O.. I didn’t want to hear your feelings and how much you liked O.. That is what I feared and that is why I said that not at that moment. You felt deeply hurt for my lack of availability. Mir. and some other facilitators passed by. We moved to a more private location.

We went to the park and you changed the strategy. You were more honest, more sincere, you started to open up. You mentioned your rituals and self-injuries. You mentioned how you saved your cat.  I was still in a playful way. I wasn’t sure if you kept on playing or not. I couldn’t know if you were performing another role or you were genuine. I was confused again, and I didn’t know how to act. I was defensive. You asked me for help, but help, control, power, energy, are expected to be found inside. That is my philosophy, that’s my spirituality. I am not a God or a guru giving you the answers, offering you excuses to exert external control over you. I am just a human talking to a human explaining that is all inside, we like it or not. You asked me why you were keep on playing, you told me that you wanted to stop playing, but I wasn’t sure whether I should believe or not. You had reminded me so many times about trust the previous day that I wanted to believe in your words. I tried and then realized that it was you the one that didn’t trust on me. “Am I playing with you?” “Yes.” “Do you trust me?” “Yes.” These two questions were denying each other.  

I had talked to you about “The Game”, about all those guys that had envisioned a huge range of techniques of strategies to transform complete strangers into loyal girlfriends. I had told you that with you I hadn’t had the need of doing any of that, that the learning was there on the back of my mind, knowing what to say and what not to say at a certain moment, but that my relationship with you from the beginning had been genuine. That I hadn’t calculated any kiss, that I had exposed myself to be rejected repeated times, that I had looked for you, that I had left you messages of vulnerability, and that I had open up led by trust, not by compromise mechanisms. I had been restless and sleepless waiting for you to appear on my room. You kept on saying that I was playing with you, and I kept on saying that you were not trusting my words. You unlock another piece of my being, a deep and profound one. 

I looked into your eyes. I was hanging from the ropes of the pyramid, you were already seated, playing with the wood. “Thank you, A.. I stop playing.” You kept on teaching me all those deep lessons, I kept on learning from you, while you complained that our encounters left you empty. The lesson is on the student, not in the teacher. You had left me extremely full and obstructed after our mountain hike. I remined you of the power of emptiness on the notes of the envelope, you My Sherpa. You seemed never satisfied, never at peace. Nothing was enough for you. On the other hand, I felt like I was continuously learning, continuously growing, expanding, transforming, improving the previous versions of myself. You were there saying that it wasn’t about me that it was about you, that you didn’t even know if you wanted to stop playing or not. As a psychologist, I learned that I cannot convince a person of anything if they don’t want to be convinced about it. I tried a bit of hypnotherapy, but you reject it automatically as well. I didn’t know what to do with you. You didn’t show any signs of cooperation, and I was already assuming that I had learned all the lessons I had to learn from that exchange. I was getting familiar with the idea of leaving the place walking during the next morning. 

You told me that I wasn’t cooperating, but I was doing my best, and if my best wasn’t enough, then my best was ready to leave you and leave that place. I was feeling deeply at peace, deeply powerful, deeply complete and finished. I told you again that we could stop playing all together and you kept on repeating that it wasn’t about me. “It is not about you, Carlos.” “I know, but we can start with me.”  But you didn’t understand. I didn’t understand. You chew those sticks of wood, that then you buried. You were embodying a regression to a previous version of your self. You were enacting a kid A. that was learning about love. The following night you confessed that you learn love from K., and two days later, I told you my believe about you that you think that the love you give is not “right” or “correct”. 

Anyways, you had repeated me many times that you wanted to come back to the hostel. So, we did. We separate again. 

I found Mir. and we continued with our previous conversation. The first thing I asked her was that in case I would leave, I wanted to leave walking. That was all, no cars, no confusions, no messages, no calls, no warnings, no anything. She said that no one had threatened me with expelling me out. She said I was spreading fake news. I didn’t want to argue. It wasn’t time for bullshit. I tried once more, with all my peace, all my inner power and control. I tried once more with all my non-violent communication. I tried to let her see what had happened along those days, how the dynamics of the group and myself had changed, how people had left and abandon the project, how they had gotten disengaged, how I had quitted, how I had learned my lesson. I tried to see if she had learned hers. She hadn’t. She told me that I had changed a lot from the first days, and I took that as a proof of my growth. She couldn’t receive my feedback, she kept on excusing herself about the benefits of going to the mountains, of being more flexible with the free time, of being less attached to their project. “Being honest and direct, I think that your fears are limiting your growth.”

She asked me who I was and what did I want. I told her that I had grown a lot, enjoyed the experience a lot and that I was ready to depart at peace. I told her that I enjoyed promoting other people’s growth and that the way to promote their growth the most was to withdraw myself from the situation. I fully believed what I was saying. We agreed that in case of leaving, I could leave walking. We agreed that I hadn’t completely decided what to do, and that I would see next morning. I had completely realized that the organizers hadn’t learned their lesson yet. I went to the room, share my thoughts with the roommates. Went to the kitchen and eat some raw vegetables and fruits.  

Then, looked for you in the room. I was on fire, I still had energy for more. I didn’t want to play with you, but just to figure it out when was going to be our last interaction and what was the healthiest level of depth and connection before our separation. I found you on the bed. You were distant. I was pure love and compassion. Mar. kept on complaining, but you protected me. You wanted me there and I stayed there. I lied next to you, offered you my love and support, and at some point, breathing in and out, I opened my soul to the world. I felt the surrender in the depths of my existence, I felt extreme sensations of bliss and peace. I felt evaporating myself on the cosmos. I was so infinitely thankful and recharged. 

Mar. came back, and she kicked me out. I was just experimenting compassion for her. There were no side feelings, just a recognition of her pain and sorrows. I thank her and leave you. I spend the rest of the evening saying goodbye to the people that had made an impact on my experience there. I said thank you to B., to Maf., to An., to Lo., to Ra., to all of those that wanted to listen to me. I was calm and firm. Expressing my decision to everyone. “The moment has arrived. I am leaving” (living?). There was no pain, no resentment, no regret. I was just assuming my lesson. I was surrendering to what life and the universe were giving to me. I didn’t want to think much about how to get to Strasbourg, or what to do there for a couple of days. I was living the present moment, being there, enjoying my farewells with all of them. Some tried to convince me. “It is only two days more” But it didn’t matter, the same way I would have fought to the last of my breaths when I was a warrior, I would have surrendered in the last of my seconds when I was a surrender. It wasn’t about the timing; it was about the decision. 

I found you with my roommates outside. I had already talked with O. in the kitchen about you and him. He couldn’t have stated me clearly that he had kissed you, whether he liked you or not, whether he had intentions towards you or not. I repeated that I knew, that I had talked with you and that it was okay. I just wanted to know, but he didn’t speak. It didn’t matter much. Whatever you would do when I left wouldn’t be part of my story, of my existence. I laugh with my roommates, we cheered with our glasses of different liquids, and I express my gratitude as I had done with the rest. “None of this wouldn’t have been possible without you”. I really meant it. In the same way that I meant leaving. I had hung the clothes a bit too late and it would take time to dry, but that would be the indicator of my departure. If people wanted me to stay, they could pour water over my clothes. 

My roommates showed their loyalty and respect by leaving me alone with you for our last night. I wasn’t sure whether you were going to stay or not. G. took a bit longer in leaving. He kept on dreaming about kissing me again, he kept on focusing on the callings of his gonads. But he understood the situation and left. We lied down and talk. I fell asleep a couple of times and dreamed about you. I had that dream where you were escaping from some beasts, maybe those dogs of your story, the ones you have talked with. In the dream, I realized that I couldn’t offer you anything else than my silent and stoic protection. I didn’t have to lift you up, or to fight your beast for you. I could just hold the beast while you get time to raise up yourself. I was there to protect you. I understood that you weren’t seeking for love, for support, for help. Just protection. To feel secure.

My signals of affection, silence and distance, opened you up little by little, and we let the passion evolved. “Hello again, A.”. You asked me to be gentler with you and you behaved more gently with me. We made love. I went to the room for some condoms, water and to wash my mouth because, green pepper smell like cabbage, you know. Then, there on the tatami and with a couple of blankets we had sex. K. interrupted us for a bit when she arrived in the car of her new boyfriend, which it also made me realized all the things that were going on in front of me and I hadn’t been able to see, like K.’s calls and talks on the phone. 

She left us and we continue our love making. I had you against the wall, I had you below me, I had you above me. I wanted to give you pleasure, lots of pleasure. At some point, I realized that I was making love with the universe. I was seeing the starts while holding your head and penetrating you. The devil that the previous day had traded for my soul was now giving me hers. I had already surrendered my soul to the world before on the bed. I had said goodbye to everyone. There was no soul to take. I was experiencing that blissful Taoist emptiness while practicing non-ejaculatory sex with you and the universe at once.

You came and, almost automatically, switched back to selfish, playing mode. But I wasn’t playing. It was too late for that. As I had told you, for me games were over, it was all real, all genuine. I had told you that you had been my most truthful relationship. The most genuine, the sincerest. In a Fake News exchange speaking about truthful relationships and wearing my *Truth is non-violent* t-shirt, the situation became even more meaningful. I had asked you where you want me to come, and I was saving it for you, for the right moment, as a reward of your collaboration, of our relationship, or your teachings. But surprisingly, your orgasms transformed you back to that old A. focused on herself and her games. It wasn’t anymore the A. I had said hello when we had started kissing passionately. But, you know, I couldn’t care less. I had done what I had to do, and life kept on developing as it had to. You talked in dreams about the piece you wanted to do with your theater classmates and how you had decided who was which animal on your imagined performance. 

You were sexually satisfied, and I had the universe above represented on the hundreds of the starts that the mountain was gifting me. All the energy of my sperm was still running through my system. I would use it tomorrow, no problem at all. It felt as if I had broken the wheel of reincarnation. As if I had reached Nirvana and was free of all suffering in the future. We slept together outside, under the blankets, naked, our bodies one next to each other. I would think about leaving the exchange once more next morning, now that I had reconnected with you, reconnected with me, and reconnected with life. I felt at peace, I felt tired, I felt your body, I felt the fresh air of the night, and the endless sky filled with stars. I fell asleep. Deeply asleep. 
