# DAY 8 – 2019-08-02 – Enjoying the exchange

I woke up several times by the sunrise. I woke up also by K.’s yoga which gave me a wonderful view of her ass, considered as a masterpiece by the most rigorous critics, and the mountain on the background. You were sleeping next to me. I fell asleep again and then I dreamed that I ejaculated on your mouth as you have asked me the previous night. I woke up confirming what I suspected. My swimming pants were filled of semen. I left you and went straight to the shower. Clean up myself, and without anything to dry, crossed the gym wetting the wood that I had tried to protect. The same wood that I had checked the first day. Lessons stuck on my back. I told you that you had missed a good one and got ready to start the day. 

I changed myself on the room and went into the kitchen to get an apple. M. T.  found me and pushed me on the chest. Just another proof of how things were getting awry. But I couldn’t care less. I had slept with you, said goodbye to everyone, and release a meaningful part of my energy few minutes ago. I looked at her with compassion, thinking how dangerous can be someone that takes apples from the kitchen for self-consumption. It made the rest of the day much funnier, since I had to use my climbing skills around the building to get the food I needed and deserved.  

I did the energizer of cooperating and trusting, of standing into each other on groups. People laugh, I enjoyed watching. I realized that I can enjoyed my experience there by being detached, by being a spectator of the show that life was offering me. For the activity of the videos, people made groups and I choose mine when I wanted, based on the people, the venue, and the location where I could place myself to work on my laptop. Eventually, I worked with An. in a text that I tried not to over-direct and control. However, I wanted things done, so I rushed a bit. An. had been lovely the previous day, while we were saying goodbye and she was high. We had hugged and smiled to each other so much that was difficult to express another thing than love to her. 

We did the text, and I prioritized my needs. I went around the rooms, talking and enjoying myself with people. I was thinking about taking a nap, but it was almost lunch time. I talked with Lu., Li., and La.. I got to know them a bit better. I told them that I had found my role and place in the project, that I was enjoying watching the performance, that I had become a spectator, free of outcome, and fully detached of the result. I was free. I was myself again, training my body skills, doing climbing exercises, balance, strength and stretch development. Everything was getting into its place again. 
At lunch, we ate together. You fed me from your food, directly with your hands. I knew we both were dirty animals; we were just there enacting it for everyone. We bit and scratch each other for a while, talk about our lives and our relationship, show affection from time to time. I felt secure and at peace, I was enjoying myself and the moment a lot. After a while, I went inside and kept on observing and admiring. I found O. talking with Ab. in Arabic and I asked them to continue for me while I finished all the vegetables that were left. I even drunk beer when you appeared, and played a bit to social games with you, O. and Irene. I was there for myself. 

After the session started, I decided to keep on focusing on me. I went to sleep and took a siesta. A siesta that felt amazingly good.

People were presenting their videos when I woke up. I could see mine and be admired at yours. I had the intuition that you had been the main brain behind it. It looked great. Somehow there was no reflection group. Neither I needed it.  

Dinner arrived, and we found each other outside under the blankets again, in our spot next to the stairs. Mar. arrived, because it wasn’t enough for her to kick me out of my room, she was feeling to attacked by me getting your attention so often. 

Then you confronted us, the positive and the negative forces, one against each other. I didn’t feel like fighting or anything similar, but you kept on pushing us. She proved herself deeply intelligent and deeply hurt, with a dark past that was affecting a promising future. K. joined us, and you proposed us to smoke. I told you to take care of me, but you partly refused the responsibility. You mentioned that, in a similar way as in the restaurant, you couldn’t be the babysitter. That is why I had to protect myself from the world. 

I didn’t smoke much, and I had already learned a lot about how to pacify myself. However, it happened what I feared. Once I remain silent, people keep on finding excuses to be annoyed by my existence. People keep on feeling uncomfortable by the fact that another human being is enjoying life so much to realms and to the extent that are unthinkable for them. In parties, people keep on asking which drugs I have taken, and I answer “water and air” admiring their disbelief. Mar. and you complained about my breath, about my most fundamental and unreducible behavior. If people complain about my way of breathing means that my existence is making them feel uncomfortable. But I was willing to take the feedback, to keep on breathing. Mar. mentioned a verse of the Tao and compared my breath with the one of a beast, and reminded me that the purest beings, newborns, breath unnoticeably. I took note.

Later on, I was so focused on myself, on my breathing, on my silence, and on my non-interruption and intervention on life and the moment, that I fully missed the fact that you wanted to lie down under the blankets, and that I had all the pillow for myself. Maybe it was a bit overacted, but at that point, it felt like the perfect lesson at the perfect timing. You and K. were questioning my altruism and kindness and I got revealed myself by showing my selfishness in holding the pillow only for myself. I didn’t know if the whole thing was going to end up in a ménage-a-trois or not. I didn’t care much. I had so much trust on myself and life that whatever the outcome I would be happy. If it weren’t for you two that night, it would be with someone else on the future. No anxiety, no trying, no effort. Just surrender and let things happened. 

We gave some feedback to each other. K. mentioned that I had to speak my mind more often, which was in direct opposition to my attempts of remaining silent. I told to Mar. to help the world on a daily basis, to be more helpful, more selfless, more altruist. You said nothing. 

K. left. Me and Mar. came back to our performance for you, but the feeling of being your actor, your puppet was too hierarchical for me. I knew your future studies as a director and I gave you a piece of it, but I wasn’t willing to give you the whole cake for free. So, I included you in the performance. After a while Mar. left, and you told me that you were coming back. I could have waited for you, but I wanted to play, I wanted to climb. I had already eaten some tomatoes from the plant, and I was thinking about challenging and discovering new ways around the building. I climbed the wall and observed the people on the gym through the window. K. was intelligent like a dolphin. You were extinct like a lynch, and I was astute like a fox. I went to your room through the window, then open the right windows of the gym for later taking the needed resources, leaving the right things on the right places. But somehow, I found you on the gym, and I found the music there, and I stayed for training and dancing. 

People was chilling around and I had lots of things to train and improve. You were moving from one place to another. I didn’t know what where your plans, so I made mines. You played songs that I didn’t like, but I didn’t say anything. I had full trust on you. People joined and danced. An., Maf., In., the Turkish drunken and clumsy one. I was just trying to keep the dance floor as sacred as possible, clean and without interfering objects or liquids, but people are careless, and they like to drink and spill over. Well, what can I do, maybe chaos is what they want? I want chaos within the order, I like sex pure, and I drink water from other people’s mouths. I started having my paranoid thoughts about end up eaten by a bunch of cannibal girls that had fallen in love with my flesh, very much inspired by Suskind. I kept on dancing, unsure of what was my role on that whole thing. I thought that you had every step planned, every movement predicted. You were doing your thing and I just had to let you do. That is what I did, I danced for myself, I danced with the girls. I could have kissed some of them, but I didn’t know about how you would take it, so I refused to do it. I didn’t know where all was going.

At some point the rest of the people entered the room. They were noisy, they weren’t dancing, they were complaining about the music. They were annoying me, but I was focused on myself, dancing and improving my moves. You remained on a side, silent and calm. Receiving some love you didn’t believe on. You went to sleep at some point, almost without saying good night. I climbed a couple of times to your room, to talk with K., to be kicked out by Mar., and to check whether you were there at all or not. I was giving you the so demanded distance, so I even didn’t try to go to your bed. I wanted to sleep with you outside, but I assumed that those weren’t your plans. 

I went out and found In. (Portugal). I had told her the day before to go and look for Canberk. She had done it with ambiguous results to my understanding. I offered her the possibility of talking about her emotions. We went outside to the stars. She talked for a while. I fell sleep. She left me. I thank the universe again the opportunity that had given me of being alive and fell asleep deeply this time, at peace, and feeling grateful and connected. 
